name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install TFLint
      run: |
        wget https://github.com/wata727/tflint/archive/master.zip
        unzip master.zip
        cd tflint-master && chmod +x install_linux.sh
        ./install_linux.sh
    - uses: ./
    - name: check directory
      run: |
        pwd
        ls
    - name: check tf file
      run: tflint ec2.tf

